services:
  - type: web
    name: medguard-backend
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
