name: ML Model CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/app/ml/**'

jobs:
  test_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ML Core
        run: |
          pip install torch scikit-learn numpy pandas

      - name: Torch Smoke Test
        run: python -c "import torch; print(f'Torch Version: {torch.__version__}')"
        continue-on-error: true
